### ISSUE TITLE
stroke placement on surface with magnet

### ISSUE THREAD

**Issue by mizo1900** [Pullusb/GP_magnet_strokes#2]
started filling an area a [front face of a box using ] using stroke placement on surface then suing the magnet brush to pull the strokes to the edges then press enter, the filling is correct at same view but in 3d the filling goes back to the world origin

draw strokes over box face using stroke placement on surface
![1](https://user-images.githubusercontent.com/91334763/143947084-7241c41e-ad3c-4d59-aa98-84d6927aaf0d.jpg)
hide the box then using magnet brush to spread out the painting stroke over the desired face area
![2](https://user-images.githubusercontent.com/91334763/143947061-75681143-604a-4dea-9a65-2af901e43767.jpg)
![3](https://user-images.githubusercontent.com/91334763/143947065-d7f284fa-a0d7-4de2-a445-8dcd3292aaed.jpg)
result without rotating the view angle
![4](https://user-images.githubusercontent.com/91334763/143947076-6bdbc760-8194-4408-a19b-7f1a761b4de2.jpg)
rotating the view angle and the painted area didn't align at same position with the face after hit enter
![5](https://user-images.githubusercontent.com/91334763/143947080-c3a14bfe-bb5d-4430-8c34-a9e1195c0c8f.jpg)
s

**Comment by Pullusb** [comment]
Going here after there's been a new issue, I realized I've never commented on this !! My apologies.
I've kind of abandonned the development of the addon not long after it's been released so I did not check the comments.

At the time you posted, I racked my brain a bit on the idea of 3D placement, but it has been planned from the start to work only on drawing plane.

Still, thank you for posting the idea back then !
And sorry again.
