### ISSUE TITLE
The magnet bursh doent show in blender 4.0

### ISSUE THREAD

**Issue by Note00123** [Pullusb/GP_magnet_strokes#3]
Hello,

The tool is working great for me, but for some reason, the magnet brush doesn’t show while I’m editing details. It still works just fine, but I have to work blind on the finer details. I saw in the video that you can indeed see the brush and even change the influence of the magnet, none of which seem to be active in my case.

![82beb82d-8b18-4d2f-8382-3e11adbe2845](https://github.com/Pullusb/GP_magnet_strokes/assets/171920638/59df0604-8078-43d6-815d-2af88cce4988)

Here is a normal brush in sculpt mode while I edit:

![9c87b5aa-e181-467a-aaa0-8d6a005e9869](https://github.com/Pullusb/GP_magnet_strokes/assets/171920638/1bd0f070-733b-4990-8547-5295fb37faa6)

When I activate the magnet brush, I can’t see the brush, nor can I use the shortcuts to increase the influence or size. If the shortcuts are working, I can’t tell either.

I love the tool; it’s really helpful. I hope this gets fixed.

**Comment by Pullusb** [comment]
Hi there !
This is one of my own tool I never use (I did it for other peoples) and I did not test anything for a very long while.
So thank you for reporting ! Happy to see it's useful to some users.

I'll check for a fix soon and let you know when it's updated.
I already have an idea of what could be the problem (API changes that in blender version at 3.6 or 4.0)

**Comment by Pullusb** [comment]
Hi @Note00123 

The addon has just been updated. As of now, it will only work in Blender 4.0 and above.

#### Version 3.0.0 update notes:
- changed: compatible with blender 4.0+ (no longer compatible with previous version)
- fixed: allow `add shortcut` on Magnet buttond in right-clic context menu

Let me know if you still have issues with the update.

Cheers !
