### ISSUE TITLE
Work in 4.3?

### ISSUE THREAD

**Issue by b4zz4** [Pullusb/GP_magnet_strokes#4]
I don't get the buttons turned on
![mpv-shot0009](https://github.com/user-attachments/assets/3ffcd0a1-6aa5-4af0-9591-d7366c790c93)

**Comment by Pullusb** [comment]
You're still using this one ? I did not plan to update originally.

I managed to make a quick port to GPv3 tonight, thanks to the API equivalence with GPv2.
Not fully tested, but don't have time to do more anyway.
